name: CI

on:
  # Trigger on all pushes and pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install toolchain
        run: |
          echo 'deb https://assets.checkra.in/debian /' | sudo tee /etc/apt/sources.list.d/checkra1n.list
          sudo apt-key adv --fetch-keys https://assets.checkra.in/debian/archive.key
          sudo apt-get update
          sudo apt-get install -y ld64 cctools-strip
      - name: Voodoo magic
        id: voodoo
        uses: actions/cache@v2
        with:
          key: ${{ github.event_name }}-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            push-${{ github.ref }}-
            push-
          path: |
            **
      - name: Checkout repository
        if: steps.voodoo.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update repository
        if: steps.voodoo.outputs.cache-hit == 'true'
        run: |
          git fetch --all
          git reset --hard origin/$(git branch --show-current)
          git submodule update --recursive --remote
      - name: Compile
        run: EMBEDDED_CC='clang-10' EMBEDDED_AR='llvm-ar-10' EMBEDDED_RANLIB='llvm-ranlib-10' make all
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: PongoOS
          path: |
            build/checkra1n-kpf-pongo
            build/Pongo
            build/Pongo.bin
            build/PongoConsolidated.bin
